const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const { getServerConfig } = require('../utils/configUtils');
const { requirePermission } = require('../utils/permissionUtils');
const { getConfiguredRanks } = require('../utils/rankUtils');
const { importExistingUsers } = require('../utils/googleWebhook');
const pending = new Map();
function k(){return `iu${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`}
function detect(member, config){ const rank=getConfiguredRanks(config).slice().reverse().find(r=>member.roles.cache.has(r.rankRoleId)); return { detectedRankKey: rank?.key||rank?.rankKey||rank?.name||'', detectedRankName: rank?.name||'', detectedRankRoleId: rank?.rankRoleId||'', detectedPermissionRoleId: rank?.permissionRoleId||''}; }
function row(id){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`importUsers:confirm:${id}`).setLabel('Confirm Import').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`importUsers:cancel:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary));}
module.exports={
 data:new SlashCommandBuilder().setName('import-users').setDescription('Import existing Discord users into Google by selected role.').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addRoleOption(o=>o.setName('role').setDescription('Role to scan').setRequired(true)).addBooleanOption(o=>o.setName('dry-run').setDescription('Preview only; defaults to true.')),
 async execute(interaction){ const config=getServerConfig(interaction.guildId); if(config.importUsers?.enabled===false)return interaction.reply({content:'Import users is disabled.',ephemeral:true}); if(!await requirePermission(interaction,'importUsers',{config}))return; await interaction.deferReply({ephemeral:true}); const role=interaction.options.getRole('role'); const dry=interaction.options.getBoolean('dry-run') ?? config.importUsers?.dryRunDefault !== false; await interaction.guild.members.fetch(); const members=interaction.guild.members.cache.filter(m=>!m.user.bot&&m.roles.cache.has(role.id)); const payload=members.map(m=>({guildId:interaction.guildId,discordId:m.id,discordUsername:m.user.tag,discordDisplayName:m.displayName,...detect(m,config),steam64:'',teamspeakId:'',importedByDiscordId:interaction.user.id,importedByUsername:interaction.user.tag,importSource:'DISCORD_ROLE',sourceRoleId:role.id,sourceRoleName:role.name})); const warnings=payload.filter(p=>!p.detectedRankKey).length; const embed=new EmbedBuilder().setTitle('Import Users Preview').setColor(0xffaa00).addFields({name:'Source role',value:`${role} (${role.id})`},{name:'Members found',value:String(payload.length),inline:true},{name:'Missing rank mapping',value:String(warnings),inline:true},{name:'Preview',value:payload.slice(0,10).map(p=>`${p.discordDisplayName}: ${p.detectedRankName||'Unknown/Pending'}`).join('\n')||'None'}); if(dry)return interaction.editReply({embeds:[embed]}); const id=k(); pending.set(id,{staffUserId:interaction.user.id,payload,roleId:role.id}); return interaction.editReply({embeds:[embed],components:[row(id)]}); },
 async handleButton(interaction){ if(!interaction.customId.startsWith('importUsers:'))return false; const [,action,id]=interaction.customId.split(':'); const state=pending.get(id); const config=getServerConfig(interaction.guildId); if(!state){await interaction.reply({content:'This import expired.',ephemeral:true});return true;} if(!await requirePermission(interaction,'importUsers',{config}))return true; if(state.staffUserId!==interaction.user.id){await interaction.reply({content:'Only the staff member who started this import can confirm it.',ephemeral:true});return true;} if(action==='cancel'){pending.delete(id);await interaction.update({content:'Import cancelled.',embeds:[],components:[]});return true;} await interaction.deferUpdate(); let res; try{res=await importExistingUsers({guildId:interaction.guildId,users:state.payload,requestedByDiscordId:interaction.user.id,requestedByUsername:interaction.user.tag});}catch(e){pending.delete(id);return interaction.editReply({content:`Import failed safely: ${e.message}`,embeds:[],components:[]});} pending.delete(id); const embed=new EmbedBuilder().setTitle('Import Users Completed').setColor(0x2f80ed).addFields({name:'Created',value:String(res.created||0),inline:true},{name:'Updated',value:String(res.updated||0),inline:true},{name:'Skipped',value:String(res.skipped||0),inline:true},{name:'Errors',value:(res.errors||[]).slice(0,10).join('\n')||'None'}); return interaction.editReply({embeds:[embed],components:[]}); }
};
