const { SlashCommandBuilder } = require('discord.js');
const { getServerConfig } = require('../utils/configUtils');
const { canManageProbation } = require('../utils/permissionUtils');
const store = require('../utils/workflowStore');
const { safeGetProbation } = require('../utils/googleWorkflowStore');
const { countExistingRideAlongs } = require('../utils/probationDataUtils');
const { addDays, logWorkflow, finishProbationPass } = require('../utils/trainingWorkflowUtils');
const { safeSubmitDepartmentEvent } = require('../utils/googleDepartmentEvents');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('probation')
    .setDescription('Track probationary officer progress.')
    .addSubcommand((s) => s.setName('status').setDescription('Show probation status.').addUserOption((o) => o.setName('officer').setDescription('Officer').setRequired(true)))
    .addSubcommand((s) => s.setName('extend').setDescription('Extend probation.').addUserOption((o) => o.setName('officer').setDescription('Officer').setRequired(true)).addIntegerOption((o) => o.setName('days').setDescription('Days to extend').setRequired(true).setMinValue(1).setMaxValue(30)).addStringOption((o) => o.setName('reason').setDescription('Reason').setRequired(true)))
    .addSubcommand((s) => s.setName('ridealong').setDescription('Record/link a probation ride-along.').addUserOption((o) => o.setName('officer').setDescription('Probationary officer').setRequired(true)).addStringOption((o) => o.setName('notes').setDescription('Notes').setRequired(true)).addUserOption((o) => o.setName('conducted-by').setDescription('Conducting officer').setRequired(false)))
    .addSubcommand((s) => s.setName('feedback').setDescription('Record probation feedback.').addUserOption((o) => o.setName('officer').setDescription('Officer').setRequired(true)).addStringOption((o) => o.setName('result').setDescription('Result').setRequired(true).addChoices({ name: 'Positive', value: 'positive' }, { name: 'Neutral', value: 'neutral' }, { name: 'Concern', value: 'concern' })).addStringOption((o) => o.setName('notes').setDescription('Notes').setRequired(true)))
    .addSubcommand((s) => s.setName('review').setDescription('Review probation.').addUserOption((o) => o.setName('officer').setDescription('Officer').setRequired(true)).addStringOption((o) => o.setName('decision').setDescription('Decision').setRequired(true).addChoices({ name: 'Pass', value: 'pass' }, { name: 'Fail cycle', value: 'fail-cycle' }, { name: 'Request removal', value: 'request-removal' })).addStringOption((o) => o.setName('notes').setDescription('Notes').setRequired(true)))
    .addSubcommand((s) => s.setName('approve-removal').setDescription('Approve removal request.').addStringOption((o) => o.setName('request-id').setDescription('Request ID').setRequired(true)))
    .addSubcommand((s) => s.setName('deny-removal').setDescription('Deny removal request.').addStringOption((o) => o.setName('request-id').setDescription('Request ID').setRequired(true))),

  async execute(interaction) {
    const config = getServerConfig(); const sub = interaction.options.getSubcommand();
    const commandOnly = ['approve-removal','deny-removal'].includes(sub) || (sub === 'review' && ['pass','request-removal'].includes(interaction.options.getString('decision')));
    if (!canManageProbation(interaction.member, config, commandOnly ? 'command' : 'officer')) return interaction.reply({ content: 'You are not authorized to manage probation.', ephemeral: true });
    await interaction.deferReply({ ephemeral: true });
    if (sub === 'status') return status(interaction, config);
    if (sub === 'extend') return extend(interaction, config);
    if (sub === 'ridealong') return ridealong(interaction, config);
    if (sub === 'feedback') return feedback(interaction, config);
    if (sub === 'review') return review(interaction, config);
    return interaction.editReply('Removal approval tracking is recorded in Google/audit; use the request ID from the command approval log.');
  }
};

async function readProbation(interaction, user) { return safeGetProbation(interaction.guildId, user.id); }
async function status(interaction, config) { const u = interaction.options.getUser('officer'); const r = await readProbation(interaction, u); if (!r) return interaction.editReply('No active probationary record found.'); const sqlRideAlongs = await countExistingRideAlongs(interaction.guildId, u.id); const rideAlongCount = sqlRideAlongs === null ? Number(r.rideAlongCount || 0) : Math.max(sqlRideAlongs, Number(r.rideAlongCount || 0)); return interaction.editReply(`Probation status for ${u}: ${r.status}\nCycle: ${r.cycleNumber}/${r.maxCycles}\nCycle end: ${r.cycleEndAt}\nRide-alongs: ${rideAlongCount}/${config.probation?.requiredRideAlongCount ?? 1}\nFeedback: ${r.feedbackCount || 0}\nNotes: ${r.notes || 'None'}`); }
async function extend(interaction, config) { const u = interaction.options.getUser('officer'); const days = interaction.options.getInteger('days'); const reason = interaction.options.getString('reason'); const r = await readProbation(interaction, u); if (!r) return interaction.editReply('No active probationary record found.'); const updated = store.upsertProbation(interaction.guildId, u.id, { cycleEndAt: addDays(r.cycleEndAt || new Date(), days).toISOString(), notes: [r.notes, reason].filter(Boolean).join('\n'), updatedBy: interaction.user.id }, { action: 'PROBATION_EXTENSION_GRANTED', actorDiscordId: interaction.user.id, reason }); await safeSubmitDepartmentEvent({ actionType: 'PROBATION_EXTENSION_GRANTED', interaction, actor: interaction.user, targetDiscordId: u.id, reason, payload: { probation: { ...r, ...updated }, days } }); await logWorkflow(interaction.guild, config, `Probation extended for ${u} by ${days} day(s). Reason: ${reason}`); return interaction.editReply(`Extended probation for ${u} to ${updated.cycleEndAt}.`); }
async function ridealong(interaction, config) { const u = interaction.options.getUser('officer'); const by = interaction.options.getUser('conducted-by') || interaction.user; const notes = interaction.options.getString('notes'); const r = await readProbation(interaction, u) || {}; const existingCount = await countExistingRideAlongs(interaction.guildId, u.id); const nextCount = Math.max(Number(r.rideAlongCount || 0), existingCount === null ? 0 : existingCount) + 1; const updated = store.upsertProbation(interaction.guildId, u.id, { rideAlongCount: nextCount, notes: [r.notes, `Ride-along by ${by.tag}: ${notes}`].filter(Boolean).join('\n'), updatedBy: interaction.user.id }, { action: 'PROBATION_RIDEALONG_LOGGED', actorDiscordId: interaction.user.id, notes }); await safeSubmitDepartmentEvent({ actionType: 'PROBATION_RIDEALONG_LOGGED', interaction, actor: interaction.user, targetDiscordId: u.id, reason: notes, payload: { probation: { ...r, ...updated }, conductedByDiscordId: by.id, existingRideAlongCount: existingCount, compatibility: 'Links/counts existing duty_ridealong_feedback where configured; does not replace existing ride-along system.' } }); await logWorkflow(interaction.guild, config, `Probation ride-along logged for ${u} by ${by}.`); return interaction.editReply(`Ride-along logged for ${u}. Count: ${updated.rideAlongCount}.`); }
async function feedback(interaction, config) { const u = interaction.options.getUser('officer'); const result = interaction.options.getString('result'); const notes = interaction.options.getString('notes'); const r = await readProbation(interaction, u) || {}; const updated = store.upsertProbation(interaction.guildId, u.id, { feedbackCount: Number(r.feedbackCount || 0) + 1, notes: [r.notes, `Feedback ${result}: ${notes}`].filter(Boolean).join('\n'), updatedBy: interaction.user.id }, { action: 'PROBATION_FEEDBACK_LOGGED', actorDiscordId: interaction.user.id, notes }); await safeSubmitDepartmentEvent({ actionType: 'PROBATION_FEEDBACK_LOGGED', interaction, actor: interaction.user, targetDiscordId: u.id, reason: notes, payload: { probation: { ...r, ...updated }, result } }); return interaction.editReply(`Feedback logged for ${u}.`); }
async function review(interaction, config) { const u = interaction.options.getUser('officer'); const m = await interaction.guild.members.fetch(u.id).catch(() => null); const decision = interaction.options.getString('decision'); const notes = interaction.options.getString('notes'); if (decision === 'pass') { if (!m) return interaction.editReply('Member not found.'); const result = await finishProbationPass({ interaction, member: m, notes }); return interaction.editReply(`Probation passed for ${u}. DM: ${result.dmSent ? 'sent' : 'failed'}.`); } const r = await readProbation(interaction, u) || {}; const action = decision === 'fail-cycle' ? 'PROBATION_CYCLE_FAILED' : 'PROBATION_REMOVAL_REQUESTED'; const updated = store.upsertProbation(interaction.guildId, u.id, { status: decision === 'fail-cycle' ? 'CYCLE_FAILED' : 'REMOVAL_REQUESTED', cycleNumber: decision === 'fail-cycle' ? Number(r.cycleNumber || 1) + 1 : r.cycleNumber, cycleStartAt: decision === 'fail-cycle' ? new Date().toISOString() : r.cycleStartAt, cycleEndAt: decision === 'fail-cycle' ? addDays(new Date(), config.probation?.cycleDays ?? 4).toISOString() : r.cycleEndAt, finalDecision: decision, notes: [r.notes, notes].filter(Boolean).join('\n'), updatedBy: interaction.user.id }, { action, actorDiscordId: interaction.user.id, notes }); await safeSubmitDepartmentEvent({ actionType: action, interaction, actor: interaction.user, targetDiscordId: u.id, reason: notes, payload: { probation: { ...r, ...updated } } }); await logWorkflow(interaction.guild, config, `Probation review for ${u}: ${decision}. Notes: ${notes}`); return interaction.editReply(`Probation review recorded for ${u}: ${decision}.`); }
